[package]
name = "spl-tlv-account-resolution"
version = "0.6.3"
description = "Solana Program Library TLV Account Resolution Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde"]
test-sbf = []

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
serde = { version = "1.0.203", optional = true }
solana-program = "2.0.0"
spl-discriminator = { version = "0.2.2", path = "../discriminator" }
spl-program-error = { version = "0.4.0", path = "../program-error" }
spl-type-length-value = { version = "0.4.3", path = "../type-length-value" }
spl-pod = { version = "0.2.2", path = "../pod" }

[dev-dependencies]
futures = "0.3.30"
futures-util = "0.3"
solana-client = "2.0.0"
solana-program-test = "2.0.0"
solana-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
